#ifndef myoptions_h
#define myoptions_h

/* Generated by myoptions.h generator - v0.8.1 */
/* https://e2002.github.io/docs/myoptions-generator.html?r=71,1,2,3,4,76,8,14,41,43,49,50,53,54,77&i=1,2,3,4,15,16,17,22,23,24,28,29,30,48,49&v=4,5,-1,255,27,26,25,32,35,33,34,14,36,13,15 */
/* Put this file next to yoRadio.ino and restart Arduino IDE. */

/* !!! Attention !!! */
/* This configuration depends on some additional libraries. Please install them using the library manager: */
/* Adafruit GFX Library, Adafruit ST7735 and ST7789 Library, OneButton, RTCLib */

/* !!! Do not be alarmed, all right, the default values ​​are not included in this file !!! */

#define DSP_MODEL			DSP_ST7789
#define I2S_DOUT			26
#define I2S_BCLK			25
#define I2S_LRC			27
#define BTN_DOWN			12
#define BTN_CENTER			35
#define BTN_UP			32
#define ENC_BTNR			37
#define ENC_BTNL			38
#define ENC_BTNB			36
#define ENC_INTERNALPULLUP			false
//#define RTC_MODULE			DS3231
//#define RTC_SDA			13
//#define RTC_SCL			15
#define BRIGHTNESS_PIN			21
#define TFT_DC              23
#define TFT_CS               22
#define TFT_RST              -1
#define TFT_MOSI              19
#define TFT_SCLK              18
#define DSP_HSPI        true

#define BATT_ADC            ADC1_CHANNEL_3
#endif
